apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tc4g9z8ce-dotnet-basic 
  janus-idp.io/tekton: tc4g9z8ce-dotnet-basic
  backstage.io/kubernetes-id: tc4g9z8ce-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tc4g9z8ce-dotnet-basic
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  